spring.application.name=back-stellar-query

# =============================================
# DATASOURCE ? USERS (puerto 5432)
# =============================================
spring.datasource.users.url=jdbc:postgresql://localhost:5432/stellar_auth
spring.datasource.users.username=sq_auth
spring.datasource.users.password=admin123
spring.datasource.users.driver-class-name=org.postgresql.Driver

# Pool HikariCP para users
spring.datasource.users.hikari.pool-name=UsersPool
spring.datasource.users.hikari.maximum-pool-size=5

# =============================================
# DATASOURCE ? GAME (puerto 5433)
# =============================================
spring.datasource.game.url=jdbc:postgresql://localhost:5433/stellar_game
spring.datasource.game.username=sq_game
spring.datasource.game.password=admin123
spring.datasource.game.driver-class-name=org.postgresql.Driver

# Pool HikariCP para game
spring.datasource.game.hikari.pool-name=GamePool
spring.datasource.game.hikari.maximum-pool-size=5

# =============================================
# JPA / HIBERNATE (global)
# =============================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# NO dejes que Hibernate toque las tablas (ya las crea el init.sql de Docker)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# =============================================
# JWT
# =============================================
# IMPORTANTE: cambia este secret en producción por uno generado con:
#   openssl rand -base64 64
jwt.secret=stellar-query-super-secret-key-at-least-32-bytes-long!
jwt.expiration=3600000
