spring.application.name=back-stellar-query

# DATASOURCE - USERS (puerto 5432)
spring.datasource.users.url=jdbc:postgresql://localhost:5432/stellar_auth
spring.datasource.users.username=sq_auth
spring.datasource.users.password=admin123
spring.datasource.users.driver-class-name=org.postgresql.Driver
spring.datasource.users.hikari.pool-name=UsersPool
spring.datasource.users.hikari.maximum-pool-size=5

# DATASOURCE - GAME (puerto 5433)
spring.datasource.game.url=jdbc:postgresql://localhost:5433/stellar_game
spring.datasource.game.username=sq_game
spring.datasource.game.password=admin123
spring.datasource.game.driver-class-name=org.postgresql.Driver
spring.datasource.game.hikari.pool-name=GamePool
spring.datasource.game.hikari.maximum-pool-size=5

# JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# DEVTOOLS
spring.devtools.restart.enabled=true

# JWT
jwt.secret=stellar-query-super-secret-key-at-least-32-bytes-long!
# 4h de validez
jwt.expiration=14400000  
