# BD de usuarios (puerto 5432)
spring.datasource.users.url=jdbc:postgresql://localhost:5432/stellar_auth
spring.datasource.users.username=sq_auth
spring.datasource.users.password=admin123
spring.datasource.users.driver-class-name=org.postgresql.Driver

# BD de juego (puerto 5433)
spring.datasource.game.url=jdbc:postgresql://localhost:5433/stellar_game
spring.datasource.game.username=sq_game
spring.datasource.game.password=admin123
spring.datasource.game.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect